services:
  kishop:
    build: .
    container_name: kishop
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - kishop:/data
    environment:
      - DB_PATH=/data/shopping.db
      - PORT=3000
    networks:
      - linuxserver
volumes:
  kishop:
networks:
  linuxserver:
    external: true

